rails-backend/config/routes.rb
Rails.application.routes.draw do

  get 'yourschedule/:id', to: 'test#schedule'


  resources :event_members
  resources :group_members
  resources :shifts
  resources :roles
  resources :events
  resources :groups
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      post '/register', to: 'users#create'
      post '/login', to: 'users#login'
      get '/user', to: 'users#show'
      get '/user-events', to: 'users#events'
      get '/your-groups', to: 'users#groups'
      post '/group-members/:id', to: 'groups#member_toggle'
      post '/event-members/:id', to: 'events#member_toggle'
      post '/user', to: 'users#update'
      get '/your-events', to: 'users#created_events'
      get '/your-shifts', to: 'users#shifts'
      get '/events', to: 'events#index'
      get '/events-upcoming', to: 'events#upcoming'
      get '/groups', to: 'groups#index'
      get '/events/:id', to: 'events#show'
      get '/groups/:id', to: 'groups#show'
      get '/roles/:id', to: 'events#roles'
      post '/roles', to: 'roles#create'
      get '/shifts/:id', to: 'events#shifts'
      post '/shifts', to: 'shifts#create'
      post '/shift/:id', to: 'users#claim'
      delete '/shift/:id', to: 'shifts#destroy'
      delete '/event/:id', to: 'events#destroy'
      delete '/group/:id', to: 'groups#destroy'
      get '/group-events/:id', to: 'groups#events'
      post '/email-group', to: 'emails#group_event'
      post '/events', to: 'events#create'

      resources :users
      resources :events
      resources :groups
      resources :group_members
    end
  end

  # , :path => "", :constraints => {:subdomain => "api"}

  # constraints subdomain: 'api' do
  #   scope module: 'api', :defaults => {:format => :json} do
  #     namespace :v1 do
  #       resources :users
  #       resources :events
  #     end
  #   end
  # end


end

rails-backend/app/models/event_member.rb
class EventMember < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

rails-backend/app/controllers/event_members_controller.rb
class EventMembersController < ApplicationController
  before_action :set_event_member, only: [:show, :edit, :update, :destroy]

  # GET /event_members
  # GET /event_members.json
  def index
    @event_members = EventMember.all
  end

  # GET /event_members/1
  # GET /event_members/1.json
  def show
  end

  # GET /event_members/new
  def new
    @event_member = EventMember.new
  end

  # GET /event_members/1/edit
  def edit
  end

  # POST /event_members
  # POST /event_members.json
  def create
    @event_member = EventMember.new(event_member_params)

    respond_to do |format|
      if @event_member.save
        format.html { redirect_to @event_member, notice: 'Event member was successfully created.' }
        format.json { render :show, status: :created, location: @event_member }
      else
        format.html { render :new }
        format.json { render json: @event_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_members/1
  # PATCH/PUT /event_members/1.json
  def update
    respond_to do |format|
      if @event_member.update(event_member_params)
        format.html { redirect_to @event_member, notice: 'Event member was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_member }
      else
        format.html { render :edit }
        format.json { render json: @event_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_members/1
  # DELETE /event_members/1.json
  def destroy
    @event_member.destroy
    respond_to do |format|
      format.html { redirect_to event_members_url, notice: 'Event member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_member
      @event_member = EventMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_member_params
      params.require(:event_member).permit(:user_id, :event_id, :creator, :admin, :notifications)
    end
end

rails-backend/app/helpers/event_members_helper.rb
module EventMembersHelper
end

rails-backend/app/views/event_members/_form.html.erb
<%= form_for(event_member) do |f| %>
  <% if event_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_member.errors.count, "error") %> prohibited this event_member from being saved:</h2>

      <ul>
      <% event_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.number_field :event_id %>
  </div>

  <div class="field">
    <%= f.label :creator %>
    <%= f.check_box :creator %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="field">
    <%= f.label :notifications %>
    <%= f.check_box :notifications %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails-backend/app/views/event_members/edit.html.erb
<h1>Editing Event Member</h1>

<%= render 'form', event_member: @event_member %>

<%= link_to 'Show', @event_member %> |
<%= link_to 'Back', event_members_path %>

rails-backend/app/views/event_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Members</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Creator</th>
      <th>Admin</th>
      <th>Notifications</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_members.each do |event_member| %>
      <tr>
        <td><%= event_member.user_id %></td>
        <td><%= event_member.event_id %></td>
        <td><%= event_member.creator %></td>
        <td><%= event_member.admin %></td>
        <td><%= event_member.notifications %></td>
        <td><%= link_to 'Show', event_member %></td>
        <td><%= link_to 'Edit', edit_event_member_path(event_member) %></td>
        <td><%= link_to 'Destroy', event_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Member', new_event_member_path %>

rails-backend/app/views/event_members/new.html.erb
<h1>New Event Member</h1>

<%= render 'form', event_member: @event_member %>

<%= link_to 'Back', event_members_path %>

rails-backend/app/views/event_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @event_member.user_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event_member.event_id %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @event_member.creator %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @event_member.admin %>
</p>

<p>
  <strong>Notifications:</strong>
  <%= @event_member.notifications %>
</p>

<%= link_to 'Edit', edit_event_member_path(@event_member) %> |
<%= link_to 'Back', event_members_path %>