rails-backend/config/routes.rb
Rails.application.routes.draw do

  get 'yourschedule/:id', to: 'test#schedule'


  resources :event_members
  resources :group_members
  resources :shifts
  resources :roles
  resources :events
  resources :groups
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      post '/register', to: 'users#create'
      post '/login', to: 'users#login'
      get '/user', to: 'users#show'
      get '/user-events', to: 'users#events'
      get '/your-groups', to: 'users#groups'
      post '/group-members/:id', to: 'groups#member_toggle'
      post '/event-members/:id', to: 'events#member_toggle'
      post '/user', to: 'users#update'
      get '/your-events', to: 'users#created_events'
      get '/your-shifts', to: 'users#shifts'
      get '/events', to: 'events#index'
      get '/events-upcoming', to: 'events#upcoming'
      get '/groups', to: 'groups#index'
      get '/events/:id', to: 'events#show'
      get '/groups/:id', to: 'groups#show'
      get '/roles/:id', to: 'events#roles'
      post '/roles', to: 'roles#create'
      get '/shifts/:id', to: 'events#shifts'
      post '/shifts', to: 'shifts#create'
      post '/shift/:id', to: 'users#claim'
      delete '/shift/:id', to: 'shifts#destroy'
      delete '/event/:id', to: 'events#destroy'
      delete '/group/:id', to: 'groups#destroy'
      get '/group-events/:id', to: 'groups#events'
      post '/email-group', to: 'emails#group_event'
      post '/events', to: 'events#create'

      resources :users
      resources :events
      resources :groups
      resources :group_members
    end
  end

  # , :path => "", :constraints => {:subdomain => "api"}

  # constraints subdomain: 'api' do
  #   scope module: 'api', :defaults => {:format => :json} do
  #     namespace :v1 do
  #       resources :users
  #       resources :events
  #     end
  #   end
  # end


end

rails-backend/app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user
  belongs_to :role

  validates :role_id, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_after_start
  
    def end_after_start
      if start_time && end_time
      errors.add(:end_time, "can't be before the start date.") if
        end_time < start_time
      end
    end
end

rails-backend/app/controllers/api/v1/shifts_controller.rb
module API::V1
  class ShiftsController < ApiController
    respond_to :json

    def create
      user = authenticate_user
      event = Event.find_by(id: params[:event_id])
      if user && event
        membership = EventMember.find_by(user_id: user.id, event_id: event.id)
        if membership && membership[:creator]
          shift = Shift.new(start_time: params[:start_time], end_time: params[:end_time],
                            role_id: params[:role_id], user_id: nil)
          if shift.save
            render json: {success: "Shift created"}
          else
            render json: {status: 'error', message: "Shift not created"}
          end
        else
          render json: {status: 'error', message: "Not authorised"}
        end
      elsif user
        render json: {status: 'error', message: "Invalid event id"}
      end
    end

    def destroy
      user = authenticate_user
      shift = Shift.find_by(id: params[:id])
      if user && shift
        event = shift.role.event
        membership = EventMember.find_by(user_id: user.id, event_id: event.id)
        if membership[:creator]
          if shift.destroy
            render json: {success: "Shift deleted"}
          else
            render json: {error: "Shift not deleted"}
          end
        else
          render json: {error: "Not authorised"}
        end
      elsif user
        render json: {error: "Invalid shift id"}
      end
    end

  end
end

rails-backend/app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:start_time, :end_time, :user_id, :role_id)
    end
end

rails-backend/app/helpers/shifts_helper.rb
module ShiftsHelper
end

rails-backend/app/views/shifts/_form.html.erb
<%= form_for(shift) do |f| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :role_id %>
    <%= f.number_field :role_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails-backend/app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

rails-backend/app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shifts</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>User</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.start_time %></td>
        <td><%= shift.end_time %></td>
        <td><%= shift.user_id %></td>
        <td><%= shift.role_id %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

rails-backend/app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Back', shifts_path %>

rails-backend/app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @shift.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @shift.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @shift.user_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @shift.role_id %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>