rails-backend/config/routes.rb
Rails.application.routes.draw do

  get 'yourschedule/:id', to: 'test#schedule'


  resources :event_members
  resources :group_members
  resources :shifts
  resources :roles
  resources :events
  resources :groups
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      post '/register', to: 'users#create'
      post '/login', to: 'users#login'
      get '/user', to: 'users#show'
      get '/user-events', to: 'users#events'
      get '/your-groups', to: 'users#groups'
      post '/group-members/:id', to: 'groups#member_toggle'
      post '/event-members/:id', to: 'events#member_toggle'
      post '/user', to: 'users#update'
      get '/your-events', to: 'users#created_events'
      get '/your-shifts', to: 'users#shifts'
      get '/events', to: 'events#index'
      get '/events-upcoming', to: 'events#upcoming'
      get '/groups', to: 'groups#index'
      get '/events/:id', to: 'events#show'
      get '/groups/:id', to: 'groups#show'
      get '/roles/:id', to: 'events#roles'
      post '/roles', to: 'roles#create'
      get '/shifts/:id', to: 'events#shifts'
      post '/shifts', to: 'shifts#create'
      post '/shift/:id', to: 'users#claim'
      delete '/shift/:id', to: 'shifts#destroy'
      delete '/event/:id', to: 'events#destroy'
      delete '/group/:id', to: 'groups#destroy'
      get '/group-events/:id', to: 'groups#events'
      post '/email-group', to: 'emails#group_event'
      post '/events', to: 'events#create'

      resources :users
      resources :events
      resources :groups
      resources :group_members
    end
  end

  # , :path => "", :constraints => {:subdomain => "api"}

  # constraints subdomain: 'api' do
  #   scope module: 'api', :defaults => {:format => :json} do
  #     namespace :v1 do
  #       resources :users
  #       resources :events
  #     end
  #   end
  # end


end

rails-backend/app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

rails-backend/app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController
  before_action :set_group_member, only: [:show, :edit, :update, :destroy]

  # GET /group_members
  # GET /group_members.json
  def index
    @group_members = GroupMember.all
  end

  # GET /group_members/1
  # GET /group_members/1.json
  def show
  end

  # GET /group_members/new
  def new
    @group_member = GroupMember.new
  end

  # GET /group_members/1/edit
  def edit
  end

  # POST /group_members
  # POST /group_members.json
  def create
    @group_member = GroupMember.new(group_member_params)

    respond_to do |format|
      if @group_member.save
        format.html { redirect_to @group_member, notice: 'Group member was successfully created.' }
        format.json { render :show, status: :created, location: @group_member }
      else
        format.html { render :new }
        format.json { render json: @group_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_members/1
  # PATCH/PUT /group_members/1.json
  def update
    respond_to do |format|
      if @group_member.update(group_member_params)
        format.html { redirect_to @group_member, notice: 'Group member was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_member }
      else
        format.html { render :edit }
        format.json { render json: @group_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_members/1
  # DELETE /group_members/1.json
  def destroy
    @group_member.destroy
    respond_to do |format|
      format.html { redirect_to group_members_url, notice: 'Group member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_member
      @group_member = GroupMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_member_params
      params.require(:group_member).permit(:user_id, :group_id, :creator, :admin, :notifications)
    end
end

rails-backend/app/helpers/group_members_helper.rb
module GroupMembersHelper
end

rails-backend/app/views/group_members/_form.html.erb
<%= form_for(group_member) do |f| %>
  <% if group_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_member.errors.count, "error") %> prohibited this group_member from being saved:</h2>

      <ul>
      <% group_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :group_id %>
    <%= f.number_field :group_id %>
  </div>

  <div class="field">
    <%= f.label :creator %>
    <%= f.check_box :creator %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="field">
    <%= f.label :notifications %>
    <%= f.check_box :notifications %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails-backend/app/views/group_members/edit.html.erb
<h1>Editing Group Member</h1>

<%= render 'form', group_member: @group_member %>

<%= link_to 'Show', @group_member %> |
<%= link_to 'Back', group_members_path %>

rails-backend/app/views/group_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Group Members</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Group</th>
      <th>Creator</th>
      <th>Admin</th>
      <th>Notifications</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_members.each do |group_member| %>
      <tr>
        <td><%= group_member.user_id %></td>
        <td><%= group_member.group_id %></td>
        <td><%= group_member.creator %></td>
        <td><%= group_member.admin %></td>
        <td><%= group_member.notifications %></td>
        <td><%= link_to 'Show', group_member %></td>
        <td><%= link_to 'Edit', edit_group_member_path(group_member) %></td>
        <td><%= link_to 'Destroy', group_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group Member', new_group_member_path %>

rails-backend/app/views/group_members/new.html.erb
<h1>New Group Member</h1>

<%= render 'form', group_member: @group_member %>

<%= link_to 'Back', group_members_path %>

rails-backend/app/views/group_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @group_member.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @group_member.group_id %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @group_member.creator %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @group_member.admin %>
</p>

<p>
  <strong>Notifications:</strong>
  <%= @group_member.notifications %>
</p>

<%= link_to 'Edit', edit_group_member_path(@group_member) %> |
<%= link_to 'Back', group_members_path %>